### PR TITLE
s/cutom/custom/

### PR DESCRIPTION
**Pull request by aabdnn**
Fix typo

### CODE REVIEW

**Comment by mtoma** [comment]
This won't work.
Can you complete the fix like this please:
```
my $value  = $cfg->val( 'ZONEMASTER', 'cutom_profiles_path' );
$value  = $cfg->val( 'ZONEMASTER', 'custom_profiles_path' ) unless ($value);
return $value;
````

**Comment by aabdnn** [comment]
I'm just submitting fixes for spelling errors. Are you trying to keep the code backwards compatible?

**Comment by mtoma** [comment]
Yes I'm trying to make the code backward compatible with all parts that are not overridden by an upgrade. So the code needs to be backward compatible with the historic database contents and I'd say config files as well. We have at least one user of the backend I'm aware of using the config files with typos and I'd wouldn't like to relay on them fixing the typos in their config files in order to keep a working setup if they upgrade at some point.

**Comment by aabdnn** [comment]
That's kind of sad. Zonemaster isn't so widely deployed, and it should be okay to make some incompatible changes early in its life, instead of carrying around baggage like this.

**Comment by mtoma** [comment]
Yes, but it is only one more line of code per typo. I think it is worth the effort.

**Comment by matsduf** [comment]
Even though Zonemaster is early in its deployment, it is important to have control over changes that are backward incompatible. At the same time, @aabdnn, you have a point that we should try to get rid of bad baggage. We should try to do this in a controlled upgrade where the incompatibility is pointed out.

**Comment by aabdnn** [comment]
Alright, there you go. It looks really ugly to me, but I've made the change.

**Comment by mtoma** [comment]
Yes, I agree Anand, it is really ugly. For now this seems to me as the only solution.
Thx for the fix.

**Pull request merged**
