### PR TITLE
 - Modify data for new engine version.

### PR DESCRIPTION
**Pull request by vlevigneron**
- fixed dotse/zonemaster-backend#337

### CODE REVIEW

**Comment by sandoche2k** [comment]
@matsduf, @mattias-p to review

**Comment by sandoche2k** [comment]
@matsduf got to verify which commit has created this issue

**Comment by matsduf** [comment]
The information on the commit has been published on dotse/zonemaster-backend#337

**Comment by vlevigneron** [comment]
@matsduf Yes we'll do our best to understand and a new issue should be raised but as we know how to "fix" it now if we generate a new data file, it should not prevent the merge of last code for the release.

**Comment by matsduf** [comment]
@vlevigneron! If we do not understand why it happens we might introduce a bad bug in Zonemaster. The following line in `t/test01.t` emits the error message:

```
        Zonemaster::Backend::TestAgent->new( { db => "Zonemaster::Backend::DB::SQLite" } )->run( $test_id );
```

**Comment by vlevigneron** [comment]
@matsduf I guess we have to modify data just because we have changed (and fixed) the way undelegated tests work now. Just try this `zonemaster-cli afnic.fr --ns ns1.nic.fr --ns ns2.nic.fr/192.134.4.1` (which is what t/test01.t does) with the 2 environnements, you'll see that the results are differents, DNS queries also.

**Comment by matsduf** [comment]
@vlevigneron! I have no problem with recreating the data as long as we understand why we should do it. It is not only that the test fails. Zonemaster crashes and spits out messages that indicate that something is incompatible. 

If you run the test with just the 72 first lines in the file, then the data file seems to be incomplete for the test and you get the following error message (no crash):

```
t/test01.t .. 1/? External query for fr, NS attempted to a.root-servers.net/198.41.0.4 while running with no_network at /usr/local/share/perl/5.22.1/Zonemaster/Engine/Zone.pm line 206.
```

If you increase that to the first 73 lines you get the crash. 

1. Is the format of the data incorrect? We should have a test of the data to make sure the format is correct.
2. Is the data incomplete? Zonemaster should not crash because of incomplete data.

**Comment by matsduf** [comment]
@mattias-p! Please update your comment! Where do you want to have `use Scalar::Util qw(blessed)`?

**Comment by mattias-p** [comment]
As @matsduf pointed out I messed up my review comment above. Sadly I can't find an edit button for the comment. This is what I meant to say:

The #337 error message complains about not finding `blessed` in `lib/Zonemaster/Backend/TestAgent.pm`. Please `use Scalar::Util qw( blessed )` there.

**Comment by vlevigneron** [comment]
@matsduf We need to recreate the data because engine behaviour has changed for undelegated tests so current recorded data are not what the engine expects with this new behaviour.

**Comment by vlevigneron** [comment]
@matsduf I also guess there is an issue in `t/test01.t` where data file is created twice instead of just once at the end of the script. So the current data file is broken, we need to re-create it.

**Comment by vlevigneron** [comment]
@mattias-p You are right, I'll add that in TestAgent.pm file.

**Comment by matsduf** [comment]
Can you please update t/test01.t too?

**Comment by vlevigneron** [comment]
@matsduf I just did it.

**Pull request merged**
