### PR TITLE
Fix issue 213

### PR DESCRIPTION
**Pull request by mtoma**

### CODE REVIEW

**Comment by mattias-p** [comment]
This looks wrong to me. #213 isn't about line termination. It's about logging internal error details instead of leaking them.

**Comment by mtoma** [comment]
Please read:
http://perldoc.perl.org/functions/die.html

**Comment by mattias-p** [comment]
Aha, now I see! This is great, but it's the solution to a different problem.

My concern in this issue is that we leak any details about the status of the service at all through the RPC-API. When the problem is related to maintenance, just knowing that it's an internal error should be enough for the user. Administrators are interested in the details of course and that's why I suggested logging such errors.

**Comment by matsduf** [comment]
@mtoma, I suggest that you rebase your branch against an updated develop branch to get rid of the conflicts. Or else we risk getting a more complex commit history.

**Comment by matsduf** [comment]
I agree with @mattias-p that much of this messages should go to the log file instead of the API user. In some of the cases the message *should* go to the both, or at least to the API user, such the message "Invalid ns_ip_pair" in  lib/Zonemaster/Backend/TestAgent.pm.

**Comment by mtoma** [comment]
The problem is that the JSON-RPC module converts any crash (perl die) in the code and sends them automatically to the API user. This is a practical solution for a simple API.
If we want to avoid this we need to catch any die message at the RPCAPI.pm level and sent them to some log module.

For me the real issue hare was that we were leaking system information about the PATH whre the software is installed including the linux username.

To fix this properly I think all the existing error messages should be given error codes and only the error codes could be sent to the user and the description to some kind of log.

i think this issue should be merged to avoid leaking system information and possibly a new one created to change the error catching mechanism in a deeper way.

**Comment by mattias-p** [comment]
I think the changes in this PR are good. However they don't fix issue 213. If a new PR is made with the commit message and branch name changed so they don't claim to fix 213, I will approve that. Also at the same time please remove the useless merge commit.

**Pull request closed without merging**
