### PR TITLE
Updated Backend Installation Instructions

### PR DESCRIPTION
**Pull request by sandoche2k**

### CODE REVIEW

**Comment by mtoma** [comment]
Hi Sandoche, Can you please resolve tho conflicts of this commit?

**Comment by sandoche2k** [comment]
Calle or Patrik will have to do it.

**Comment by cdybedahl** [comment]
I'm not sure if we can, actually. The expected way to fix it is for you to make one or more new commits in the same branch the pull request is made from and then push those to Github. They'll show up in the pull request automatically. Alternatively, Michal can pull the commits in the pull requests into a new local branch, resolve the conflicts, push the result to Github and then just delete the pull request.

**Comment by pawal** [comment]
Yes, you should resolve any conflicts @sandoche2k.

**Comment by mtoma** [comment]
Hi Sandoche,

Do you want me to solve the conflicts?

Michal

----- Original Message -----

**Comment by sandoche2k** [comment]
Hi Michal,

     If its not affecting your holidays :-)

     Otherwise i will do it.

     FYI : I am down with fever and will not be in Afnic until wednesday.

**Comment by sandoche2k** [comment]
Shouldn't it be "cpan -i"?

*Install CPAN dependencies*

A few packages have not been installed:

$ sudo capn -i Zonemaster (follow the zonemaster-engine installation
instructions)
$ sudo capn -i JSON::RPC::Dispatch
$ sudo capn -i Plack::Middleware::Debug
$ sudo cpan -i Store::CouchDB (if you want to test the CouchDB support)

**Comment by mtoma** [comment]
it should. I'll fix this.

----- Original Message -----

**Comment by sandoche2k** [comment]
I have .. wait for my push...

**Pull request closed without merging**
