### PR TITLE
Numbered headlines and TOC

### PR DESCRIPTION
**Pull request by matsduf**
Updated installation instructions with numbered headlines and a table of contents in the beginning of the file to make it easy to find relevant section and to get an overview.

### CODE REVIEW

**Comment by mattias-p** [comment]
I don't like the idea of having to maintain such a table by hand. I'm in favor if there are good tools for generating the TOC and for checking those links. Otherwise I'm against.

**Comment by matsduf** [comment]
@mattias-p, I just created the TOC and it was not complicated. The editor provides the link target and validates the links. For Backend it think it would be an improvement.

@sandoche2k, what do you think?

**Comment by mattias-p** [comment]
@matsduf I'm worried that we'll forget to update the TOC when we update the document, and that it'll be bothersome to check whether we've forgotten or not. Apart from that I like the TOC. Oh, and with the TOC in place most of the text in the "Overview" section could be removed as it's just an enumeration of what you'll find in the document.

**Comment by matsduf** [comment]
@mattias-p, I think there is no risk that we will forget since the TOC sits in the top of the document. I was not cumbersome to create the TOC. Yes, we could reduce the "Overview". I have included a proposal.

@sandoche2k, can you review?

**Pull request merged**
