### PR TITLE
Revert "Deprecate validate_syntax"

### PR DESCRIPTION
**Pull request by pamasse**
Reverts dotse/zonemaster-backend#406

### CODE REVIEW

**Comment by matsduf** [comment]
@mattias-p, is this the best way of handling the situation?

**Comment by mattias-p** [comment]
@matsduf Yes. It can be merged straight into the develop branch and we don't have to wait for anything.

**Comment by pamasse** [comment]
I already prepare the correct PR (based on the Develop branch)

**Comment by sandoche2k** [comment]
merge?

**Comment by matsduf** [comment]
Yes, it could be merged.

**Pull request merged**
