### PR TITLE
Zonemaster backend issue 337

### PR DESCRIPTION
**Pull request by vlevigneron**

### CODE REVIEW

**Comment by sandoche2k** [comment]
@vlevigneron can you have a look at Mats request above. Also, do you have an idea why there was no issue for the current 'master' version, and not for the current 'develop' branch. Has there been any change?

**Comment by vlevigneron** [comment]
It's worst, I broke the rebase it seems... :-/

**Comment by vlevigneron** [comment]
The easier is to give up that ¨PR and do another one with just new data.

**Comment by sandoche2k** [comment]
closes #339 due to multiple commits together

**Pull request closed without merging**
